spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/fitness_db
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop

management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: "always"
